name: FreeBooks
main: org.burrow_studios.spigot.freebooks.Main

version: ${project.version}

api-version: 1.20
description: ${project.description}

authors:
  - nicosleax
  - TurtleException

commands:
  book:
    usage: "/book"

website: https://github.com/PhoenixInteractiveStudios/FreeBooks
